config/routes.rb
Workspace::Application.routes.draw do
    
  get "/sign_out"               => "sessions#destroy", as: :sign_out
  get "/auth/shopify"           => "sessions#create",  as: :omniauth_shopify
  get "/auth/shopify/callback"  => "sessions#create",  as: :omniauth_shopify_callback

  resources :shops, path: '/' do
    post "webhooks/app_uninstalled"
    post "webhooks/shop_update"
    post "webhooks/products_create"
    post "webhooks/products_update"
    post "webhooks/products_delete"
    post "webhooks/collections_create"
    post "webhooks/collections_update"
    post "webhooks/collections_delete"
    resources :smart_collections,  controller: 'collections', type: 'SmartCollection', only: [:create, :destroy]
    resources :custom_collections, controller: 'collections', type: 'CustomCollection', only: [:create, :destroy]
  end
  
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  
  after_create :register_webhooks
  after_create :reload_shopify

  def self.create_with_omniauth(auth)
    create! do |shop|
      shop.uid   = auth["uid"]
      shop.token = auth["credentials"]["token"]
    end
  end

  def self.find_by_omniauth(auth)
    shop = Shop.find_by_uid(auth["uid"])
    return nil if shop.nil?
    
    shop.update(token: auth["credentials"]["token"]) unless shop.token == auth["credentials"]["token"]
    shop
  end
  
  def shopify
    @shopify ||= self.api { ShopifyAPI::Shop.find(:one, from: "/admin/shop.json", uid: self.uid) }
  end
  
  def shopify_smart_collections
    @shopify_smart_collections ||= self.api {ShopifyAPI::SmartCollection.find(:all, uid: self.uid) }
  end
  
  def shopify_custom_collections
    @shopify_custom_collections ||= self.api {ShopifyAPI::CustomCollection.find(:all, uid: self.uid) }
  end
  
  def reload_shopify
    @shopify = self.api { ShopifyAPI::Shop.find(:one, from: "/admin/shop.json", uid: self.uid, reload: true) }
  end
  
  def reload_shopify_smart_collections
    @shopify_smart_collections = self.api {ShopifyAPI::SmartCollection.find(:all, uid: self.uid, reload: true) }
  end
  
  def reload_shopify_custom_collections
    @shopify_custom_collections = self.api {ShopifyAPI::CustomCollection.find(:all, uid: self.uid, reload: true) }
  end
  
  def api(&block)
    output = nil
    ShopifyAPI::Session.temp(self.uid, self.token) do 
      output = yield
    end
    return output
  end
  
  def collections
    collections = Array.new
    
    shopify_smart_collections.each do |shopify_collection|
      new_collection   = SmartCollection.find_by(shop_id: self.id, id: shopify_collection.id)
      new_collection ||= SmartCollection.new(shop_id: self.id, id: shopify_collection.id)
      collections << new_collection
    end

    shopify_custom_collections.each do |shopify_collection|
      new_collection   = CustomCollection.find_by(shop_id: self.id, id: shopify_collection.id)
      new_collection ||= CustomCollection.new(shop_id: self.id, id: shopify_collection.id)
      collections << new_collection
    end
    
    collections
  end
  
  def register_webhooks
    self.api do
      ShopifyAPI::Webhook.create(topic: 'shop/update', address: shop_webhooks_shop_update_url(self.id), format: 'json')
      ShopifyAPI::Webhook.create(topic: 'app/uninstalled', address: shop_webhooks_app_uninstalled_url(self.id), format: 'json')

      ShopifyAPI::Webhook.create(topic: 'collections/create', address: shop_webhooks_collections_create_url(self.id), format: 'json')
      ShopifyAPI::Webhook.create(topic: 'collections/update', address: shop_webhooks_collections_update_url(self.id), format: 'json')
      ShopifyAPI::Webhook.create(topic: 'collections/delete', address: shop_webhooks_collections_delete_url(self.id), format: 'json')
    end
  end
  
  def method_missing(method, *args)
    unless self.new_record?
      return shopify.attributes[method] if shopify.attributes.include?(method)
    end
    super
  end
  
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: :show

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
  end

  private
    def set_shop
      @shop = Shop.find(params[:id])
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/index.html.erb
<div class="page-header">
  <h1>Listing Shops</h1>
</div>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= link_to shop.name, shop %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<form role="form" action="<%= omniauth_shopify_path %>" method="get">
  <div class="input-group">
    <input type="text" class="form-control" name="shop">
    <span class="input-group-btn">
      <input class="btn btn-default" type="submit" value="Install">
    </span>
  </div>
</form>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<div class="page-header">
  <h1><%= @shop.name %> <small><%= @shop.uid %></small></h1>
</div>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shop.collections.each do |collection| %>
      <% next if collection.generated? %>
      <tr>
        <td><%= collection.title %></td>
        <td>
          <% if collection.sortable? %>
            <%= button_to 'Remove', send("shop_" + collection.type.underscore + "_path", @shop, collection), method: :delete, class: 'btn btn-danger' %>
          <% else %>
            <%= render 'collections/form_create',  { collection: collection } %>
          <% end %>
        </td>
      </tr>
    <% end %>
    
  </tbody>
</table>